### ISSUE TITLE
Libellés polygones

### ISSUE THREAD

**Issue by yohanboniface** [tilery/pianoforte#1]
En l'état ils créent trop de bruit, il faudrait les distinguer un peu plus.
Problème: l'italique et les majuscules n'existent pas en arabe.

![screenshot-20171031113716-1312x1497](https://user-images.githubusercontent.com/146023/32219856-e0c3ce2e-be2f-11e7-8436-bb05a91ba330.png)

**Comment by yohanboniface** [comment]
Trying with condensed font:

![screenshot-20171031123458-1371x1512](https://user-images.githubusercontent.com/146023/32222046-06e15128-be38-11e7-8c74-d3ac4c84cea1.png)

**Comment by yohanboniface** [comment]
Trying to encrease village type:

![screenshot-20171031123529-1396x1541](https://user-images.githubusercontent.com/146023/32222090-2ff27858-be38-11e7-9b5d-7b8fdf4c3ce9.png)

**Comment by kent1D** [comment]
And decreasing a bit woods and golfs which are (for golfs at least) less imprtant isn’t it?

**Comment by kent1D** [comment]
Station d’épuration at this zoom level doesn’t seem to be so pertinent also.

**Comment by yohanboniface** [comment]
> And decreasing a bit woods and golfs which are (for golfs at least) less imprtant isn’t it?

They are already in Light. If I move down to ExtraLight, readability suffers:

![screenshot-20171031132923-1480x1480](https://user-images.githubusercontent.com/146023/32223896-89af8f14-be3f-11e7-9357-2798d8215f39.png)


> Station d’épuration at this zoom level doesn’t seem to be so pertinent also.

Yes :)
For now the rule is quite dumb: if the area is big enough (>500.000m2) and if there is no other label around, we display it. I think filtering by category can come in a later step (in this case, this is a landuse=industrial, I'm quite sure we'll want some other landuse=industrial label to be displayed)

**Comment by kent1D** [comment]
I meant in font size for the decrease, but I’m not in front of a computer to see if it would be readable

**Comment by yohanboniface** [comment]
> I meant in font size for the decrease, but I’m not in front of a computer to see if it would be readable

There is already one point difference between villages and areas, decreasing areas font size by one point more seems a bit too much, but why not:

![screenshot-20171031133842-1437x1399](https://user-images.githubusercontent.com/146023/32224217-d7bb6fb0-be40-11e7-9c89-6ab8aa540c3d.png)

We may try the other way, by increasing the village font size, but this is playing with fire (bigger means more conflicts):
![screenshot-20171031134542-1446x1333](https://user-images.githubusercontent.com/146023/32224461-d272e852-be41-11e7-947f-b7f84443525a.png)

**Comment by yohanboniface** [comment]
Darkening a bit villages and cities seem the best move:

![screenshot-20171031140100-1433x1405](https://user-images.githubusercontent.com/146023/32225019-f2c87886-be43-11e7-99da-87b1cd435a80.png)
