### ISSUE TITLE
lwpoly_from_lwlines: shell must be closed

### ISSUE THREAD

**Issue by kent1D** [tilery/pianoforte#17]
Working on my branch here : https://github.com/kent1D/pianoforte/tree/fix_boundaries_script

I have this error on 2 countries (Germany and Russia) in the script make_boundaries.py : 

`asyncpg.exceptions.InternalServerError: lwpoly_from_lwlines: shell must be closed`

After some search, shouldn't we use something like that to be sure the multipolyline is closed : https://postgis.net/docs/ST_AddPoint.html

**Comment by kent1D** [comment]
I am too newbie to manage it

**Comment by yohanboniface** [comment]
This certainly means there is an issue in the retrieved data. First thing should be to have a look at it to understand a bit how you get in that situation.
Then http://postgis.net/docs/ST_MakeValid.html may be an option to work around some issues.

**Comment by yohanboniface** [comment]
http://overpass-turbo.eu/s/vzJ may help you dig in the data with an interface if you are not comfortable with inspecting from python directly :)

**Comment by kent1D** [comment]
Mmmh

This morning, it works for Germany and Russia but not for Brazil for example :(

**Comment by kent1D** [comment]
The content from http://overpass-turbo.eu/s/vzM is not the same retrieved via the API also. Both don't work

**Comment by kent1D** [comment]
On overpass there is an extra point not necessary on the left of Brazil which seems to be related with this change : http://www.openstreetmap.org/changeset/55830849#map=10/-3.9060/-69.2420

**Comment by yohanboniface** [comment]
Living data ;)
This is one of the reasons why the data is cached.
See also http://www.openstreetmap.org/changeset/55292414

**Comment by yohanboniface** [comment]
This way is missing the "outer" role in the relation: http://www.openstreetmap.org/way/556484536

**Comment by yohanboniface** [comment]
Fixed http://www.openstreetmap.org/changeset/55889903

**Comment by kent1D** [comment]
Perfect, now the script works.

I clean a bit an pull request.

Thanks

**Comment by kent1D** [comment]
I will need some lessons of data structure, or read a book
