### ISSUE TITLE
Filter area labels at zoom 12

### ISSUE THREAD

**Issue by yohanboniface** [tilery/pianoforte#3]
from #1 discussion.

**Comment by yohanboniface** [comment]
Those are all types we are targetting in landuses:

```
      landuse: [park, forest, residential, retail, commercial, industrial, railway,
        cemetery, grass, farmyard, farm, farmland, orchard, vineyard, wood, meadow,
        village_green, recreation_ground, allotments, quarry]
      leisure: [park, garden, golf_course]
      natural: [wood, land]
```

Comparing labels and related types:

![screen shot 2017-10-31 at 14 50 19-fullpage](https://user-images.githubusercontent.com/146023/32227165-d66d4f0c-be4a-11e7-9cc5-f77b0d239955.png)

I'm tempted to say, let's display all starting at zoom 13, but for zoom 12, let's keep: park, forest, residential, commercial, industrial, wood.

Thoughts?

**Comment by yohanboniface** [comment]
Made a first shot, but it can be refined :)

**Comment by kent1D** [comment]
Thx, lets see it in action an refine then
