### ISSUE TITLE
Strange labels on regions

### ISSUE THREAD

**Issue by kent1D** [tilery/pianoforte#35]
Working on the visibility of regions, I see some problems here in Spain at least.

<img width="1440" alt="capture d ecran 2018-04-28 a 10 54 10" src="https://user-images.githubusercontent.com/178744/39394456-93d24200-4ad2-11e8-82cb-3d8b07611199.png">

In the north west part (Galicia), the name of islands / islets are shown (Illa mediana de Sisargas...)

They shouldnt.

I don't know if it's a problem in OSM tags or in our code.

CF : https://www.openstreetmap.org/way/18793204 it is a way. Should'nt we have only relations in this? or could we add "place" tag to filter these?

**Comment by yohanboniface** [comment]
> In the north west part (Galicia), the name of islands / islets are shown (Illa mediana de Sisargas...)

Weird tagging.
The example you point comes from https://www.openstreetmap.org/changeset/53959739, made by edvac which is a long time contributor.
For me, administrative=boundary and admin_level=4 should only be on the relation, not on the ways. Like here for example: https://www.openstreetmap.org/way/504643799
Let's ask him directly.

**Comment by yohanboniface** [comment]
(Ah, there is already one comment on the changeset!)

**Comment by kent1D** [comment]
I have a patch. In osm carto (the default theme) they filter regions with osm_id > 0. Which seems to work.

There are also this kind of problem in Italy at least

**Comment by yohanboniface** [comment]
> I have a patch. In osm carto (the default theme) they filter regions with osm_id > 0. 

Humm, I think this is specific to osm2pgsql, which makes relation id negative to prevent id clash (given a way, a node and a relation can have the same id).
Not sure this will work with imposm.

**Comment by kent1D** [comment]
On my local import with imposm (Only Europe), I have these negative ids and it seems to work

For Galicia :

<img width="1336" alt="capture d ecran 2018-04-30 a 08 53 59" src="https://user-images.githubusercontent.com/178744/39417367-0da15896-4c54-11e8-89f7-7e9fb6b65984.png">

**Comment by kent1D** [comment]
And Italy :

<img width="1322" alt="capture d ecran 2018-04-30 a 08 55 45" src="https://user-images.githubusercontent.com/178744/39417414-5072821c-4c54-11e8-8d56-58a79f8e70b0.png">

**Comment by kent1D** [comment]
After that I don't say that this isn't a bug in tags ;)

**Comment by yohanboniface** [comment]
I see three separate questions to proceed:

- whether this is an accepted way of tagging or not (i.e. adding boundary+admin_level to a way which is part of an admin boundary but NOT an admin boundary per se)
- whether there are cases where an admin boundary IS a way and not a relation (small counties, island countries…)
- whether we do want to filter out non relations from admin boundaries, and if so is there a less hackish way to do so

**Comment by yohanboniface** [comment]
For reference https://www.openstreetmap.org/changeset/41156298#map=8/40.085/8.971
