### ISSUE TITLE
La comparaison sur la capitale ne peut fonctionner correctement

### ISSUE THREAD

**Issue by kent1D** [tilery/pianoforte#36]
https://github.com/tilery/pianoforte/blob/28c745ddd70931c73a42feb6a78eb1b8af6d1346/forte.yml#L314

Si le champ capital est vide, il passe avant les autres. D'autre part, ce champ n'est pas typé, yes pour la capitale d'un pays puis normalement l'admin_level. Mais n'importe qui peut y mettre ce qu'il veut.

**Comment by yohanboniface** [comment]
> Si le champ capital est vide

`NULLS LAST` ? :)
