### ISSUE TITLE
Slow loading Forte tiles

### ISSUE THREAD

**Issue by Omega933** [tilery/pianoforte#55]
Since January 1, 2024, I have noticed that Forte tiles load very slowly. There were no problems before this date. What is the reason for this?

**Comment by yohanboniface** [comment]
Seems to be loading as usual for me. Can you test from another network (work/home/phone…) ?

**Comment by Omega933** [comment]
I tested this on various devices and network and the tiles load slower than last year.

I'm testing Forte on umap and https://newsmap.pl/newsmap/ with Forte tiles.

**Comment by yohanboniface** [comment]
May be related to your location. Where are you located ?

**Comment by Omega933** [comment]
Poland. Can the location problem be solved?

**Comment by yohanboniface** [comment]
What is newsmap.pl ? Do you know what's the audience ? Quite a lot of requests are coming from this origin.

**Comment by Omega933** [comment]
This is Ukraine War Map. Audience for this map is 8K views per week.
